version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/payments
      - REDIS_URL=redis://redis:6379
      - WEBHOOK_SECRET=super_secret_key@@@@
    depends_on:
      - mongodb
      - redis
    restart: always

  mongodb:
    image: mongo:7.0
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    restart: always

  redis:
    image: redis:7.2-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: always

volumes:
  mongo_data:
  redis_data:
